apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahl-ms-detalle-periodo-hl-java-deployment
  namespace: NAMESPACE_AKS
  labels:
    app: ahl-ms-detalle-periodo-hl-java-deployment
    domain: NAMEDOMAIN
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ahl-ms-detalle-periodo-hl-java-deployment
  template:
    metadata:
      labels:
        app: ahl-ms-detalle-periodo-hl-java-deployment
        domain: NAMEDOMAIN
    spec:
      nodeSelector:
        'beta.kubernetes.io/os': linux
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: NAMESECRETPROVIDERCLASS
      containers:
        - name: ahl-ms-detalle-periodo-hl-java-deployment
          image: azuepvgoydvpsptacr.azurecr.io/NAME_ARTIFACT:VERSION
          volumeMounts:
            - name: secrets-store
              mountPath: '/mnt/secrets-store'
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 600m
              memory: 600Mi
          ports:
            - containerPort: 8080
          env:
            - name: APPVER
              value: 'VERSION'
            - name: VERDATE
              value: 'GENERACION'
            - name: ENV
              value: 'dev'
            - name: PORT
              value: '80'
            - name: DATABASEURL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: DB-URL
            - name: DATABASEUSER
              valueFrom:
                secretKeyRef:
                  name: db-username
                  key: DB-USERNAME
            - name: DATABASEPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB-PASSWORD
            - name: DATABASEDRIVER
              value: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
            - name: DATABASEPOOLSIZE
              value: '1'
            - name: DATABASETIMEOUT
              value: '5'
            - name: ACTIVE_LOG
              value: 'true'
            - name: END_POINT_WS_LOG
              value: 'Endpoint del coletor de trazas de error'
            - name: CORS
              value: '*'
            - name: CACHE
              value: '0 * * ? * *'
            - name: TIMEOUTLOGS
              value: '5000'
---
apiVersion: v1
kind: Service
metadata:
  name: ahl-ms-detalle-periodo-hl-java-services
  namespace: NAMESPACE_AKS
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ahl-ms-detalle-periodo-hl-java-deployment